"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='pymapbox',
    description='This is a thin python wrapper for mapbox. It generates javscript to execute mapboxgl and create mapbox maps.',
    version='0.0.1',
    url='https://github.com/simonm3/pymapbox.git',
    install_requires=['yatl', 'shapely', 'geopandas', 'pyyaml', 'tqdm', 'folium', 'fuzzywuzzy',
                      'plotly', 'geopy', 'ipyleaflet', 'numpy', 'pandas', 'scipy', 'colour', 'ipython'],
    packages=['pymapbox', 'pymapbox.elections'],
    package_data={'pymapbox/elections': ['elections.html', 'elections.rst']},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
