"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name='mapboxer',
    description='mapboxer',
    version='0.0.0',
    url='',
    install_requires=['ipython', 'pandas', 'geopandas',
                      'yatl', 'colour', 'pyyaml', 'plotly'],
    packages=['mapboxer', 'mapboxer.elections'],
    package_data={'mapboxer': ['base.css', 'base.html']},
    include_package_data=True,
    py_modules=[],
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
